name: CompanionAI
version: 1.2.1
main: me.bray.companionai.CompanionAI
api-version: '1.20'
depend: [Citizens]

commands:
  companion:
    description: Companion command
    usage: /companion

permissions:
  companion.use:
    default: true

  companion.admin:
    default: op